import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';

interface planet {
  name: string;
  climate: string;
  diameter: string;
  gravity: string;
  orbital_period: string;
  population: string;
  rotation_period: string;
  surface_water: string;
  terrain: string;
}

const MainStyled = styled.main`
  align-items: center;
  display: flex;
  flex: 1;
  flex-direction: column;
  justify-content: center;
  min-height: 100vh;
  padding: 4rem 0;
`;

const Home: NextPage = () => {
  const [data, setData] = useState<planet[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const route = useRouter();

  const getData = async () => {
    try {
      setLoading(true);
      let allData: planet[] = [];
      let nextPage = 'https://swapi.dev/api/planets/';

      while (nextPage) {
        const res = await axios.get(nextPage);
        const { results, next } = res.data;

        allData = allData?.concat(results);

        nextPage = next;
      }

      setData(allData);
      setLoading(false);
    } catch (err) {
      console.error(err);
      setLoading(false);
    }
  };

  useEffect(() => {
    getData();
  }, []);

  const goDetail = (index: number) => {
    console.log(index);
    route.push(`/DetailPlanet/${index + 1}`);
  };

  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        'loading...'
      ) : (
        <MainStyled>
          <h1 className="text-3xl font-bold underline">Planet List</h1>

          <div className={styles.grid}>
            {data?.map((item, index) => (
              <div className={styles.card} key={index} onClick={() => goDetail(index)}>
                <h2>{item?.name}</h2>
                <p>climate : {item?.climate}</p>
                <p>Diameter : {item?.diameter}</p>
                <p>gravity : {item?.gravity}</p>
                <p>Orbital Periode : {item?.orbital_period}</p>
                <p> Population : {item?.population}</p>
                <p>Rotation Periode : {item?.rotation_period}</p>
                <p>Surface Water: {item?.surface_water}</p>
                <p>Terrain : {item?.terrain}</p>
              </div>
            ))}
          </div>
        </MainStyled>
      )}
    </div>
  );
};

export default Home;
